/* Description: Pressing BUTTON1 toggles RED LED and pressing BUTTON2
 * the GREEN LED. Implemented using interrupts.
 * Adapted from code listing 6.10 (p. 100) from the textbook.
 *
 * Author: Giri Prabhu
 * Modified: Naga Kandasamy, July 16, 2019
*******************************************************************************/

/* DriverLib includes. */
#include <ti/devices/msp432p4xx/driverlib/driverlib.h>

/* Standard includes. */
#include <stdint.h>
#include <stdbool.h>

uint8_t status_1 = 0;
uint8_t status_4 = 0;

int main (void)
{
    /* Stop Watchdog timer. */
    MAP_WDT_A_holdTimer ();

    /* Configure the output GPIO pins driving the LEDs. */
    GPIO_setAsOutputPin (GPIO_PORT_P2, GPIO_PIN0 | GPIO_PIN1);
    GPIO_setOutputLowOnPin (GPIO_PORT_P2, GPIO_PIN0 | GPIO_PIN1);

    /* Configure input GPIO pins, P1.1 for BUTTON1 and BUTTON2 P1.4. */
    GPIO_setAsInputPinWithPullUpResistor(GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    GPIO_interruptEdgeSelect(GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4, GPIO_LOW_TO_HIGH_TRANSITION);
    GPIO_clearInterruptFlag(GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    GPIO_enableInterrupt(GPIO_PORT_P1, GPIO_PIN1 | GPIO_PIN4);
    Interrupt_enableInterrupt(INT_PORT1);
    Interrupt_enableMaster();

    int counter = 0;
    while (1)
    {
        if(status_1)
        {
            counter++;
            status_1 = 0;
        }
        else if(status_4)
        {
            counter--;
            status_4 = 0;
        }

        if(counter > 0)
        {
            GPIO_setOutputHighOnPin(GPIO_PORT_P2, GPIO_PIN1);
            GPIO_setOutputLowOnPin(GPIO_PORT_P2, GPIO_PIN0);
        }
        else if(counter < 0)
        {
            GPIO_setOutputHighOnPin(GPIO_PORT_P2, GPIO_PIN0);
            GPIO_setOutputLowOnPin(GPIO_PORT_P2, GPIO_PIN1);
        }
        else
        {
            GPIO_setOutputLowOnPin(GPIO_PORT_P2, GPIO_PIN1);
            GPIO_setOutputLowOnPin(GPIO_PORT_P2, GPIO_PIN0);
        }
    }
}

/* ISR to handle IRQs generated by pins in PORT1. */
void PORT1_IRQHandler(void)
{
    uint16_t status = GPIO_getEnabledInterruptStatus (GPIO_PORT_P1);
    GPIO_clearInterruptFlag (GPIO_PORT_P1, status);

    /* Check for the correct pin that generated the interrupt. */
    if (status & GPIO_PIN1)
        status_1 = 1;
    else if (status & GPIO_PIN4)
        status_4 = 1;

    return;
}
